MODELIX-577 Add ModelQL v2 support to model-server
modelix/modelix.core pull request #295
Opened 2023-10-23 14:48 UTC by slisson

The endpoint was already implemented on the server side, but there was no method on the client side to call it.

2023-10-23 15:03 UTC, languitar requested changes
Some remarks inline.

Apart from that: what is the difference between ModelQlClient and ModelClientV2? Can `ModelQlClient` also be used with the model-server?

2023-10-24 15:06 UTC, slisson commented on model-server/src/main/kotlin/org/modelix/model/server/handlers/ModelReplicationServer.kt
> +                //      change, but should be done in some future version.
At the moment it's the same, but this may change when implementing permission checks. This whole "versions" route will probably be removed then.

2023-10-24 15:06 UTC, slisson commented on model-server/src/main/kotlin/org/modelix/model/server/handlers/ModelReplicationServer.kt
> +                            TODO()
It's not used by the client yet. It's copied from the route without a repository ID. I just didn't want to delete it.

2023-10-24 15:15 UTC, slisson commented on model-server/src/main/kotlin/org/modelix/model/server/handlers/ModelReplicationServer.kt
> +                            //      A check if the version belongs to the repository is required.
https://issues.modelix.org/issue/MODELIX-585/Add-permission-checks-to-the-ModelClientV2

2023-10-25 06:58 UTC, languitar approved these changes
Looks fine to me now.

Can you provide an answer to my question from above:

> Apart from that: what is the difference between ModelQlClient and ModelClientV2? Can ModelQlClient also be used with the model-server?

2023-10-25 07:51 UTC, slisson commented
There is the `ModelQLServer` class that implements the `/query` endpoint in the model-server and the light-model-server (MPS plugin). `ModelQLClient` is the client part that calls this endpoint and is a class used internally by the different clients that have knowledge about the location of that endpoint. You wouldn't use the `ModelQLClient` directly, but some `query` method provided by the other clients.

2023-10-25 07:51 UTC, merged

2023-10-25 07:52 UTC, slisson commented
:tada: This PR is included in version 3.7.0 :tada:

The release is available on [GitHub release](https://github.com/modelix/modelix.core/releases/tag/3.7.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: