fix(model-server): writing to a branch using the v1 API failed
modelix/modelix.core pull request #338
Opened 2023-11-27 10:14 UTC by slisson

Ignite doesn't support nested transactions. Starting a transaction from inside a transaction throws the following exception:

java.lang.IllegalStateException: Failed to start new transaction (current thread already has a transaction): ...
	at org.apache.ignite.internal.processors.cache.transactions.IgniteTransactionsImpl.txStart0(IgniteTransactionsImpl.java:184)
	at org.apache.ignite.internal.processors.cache.transactions.IgniteTransactionsImpl.txStart(IgniteTransactionsImpl.java:70)
	at org.modelix.model.server.store.IgniteStoreClient.runTransaction(IgniteStoreClient.kt:139)
	at org.modelix.model.server.handlers.RepositoriesManager.mergeChanges(RepositoriesManager.kt:151)
	at org.modelix.model.server.handlers.KeyValueLikeModelServer$putEntries$1.invoke(KeyValueLikeModelServer.kt:323)
	at org.modelix.model.server.handlers.KeyValueLikeModelServer$putEntries$1.invoke(KeyValueLikeModelServer.kt:316)
	at org.modelix.model.server.store.IgniteStoreClient.runTransaction(IgniteStoreClient.kt:140)
	at org.modelix.model.server.handlers.KeyValueLikeModelServer.putEntries(KeyValueLikeModelServer.kt:316)
	at org.modelix.model.server.handlers.KeyValueLikeModelServer$modelServerModule$1$3$7.invokeSuspend(KeyValueLikeModelServer.kt:163)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda$1$lambda$0(NettyApplicationEngine.kt:296)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

2023-11-27 11:00 UTC, odzhychko approved these changes

2023-11-27 11:27 UTC, languitar requested changes
A test verifying this bug fix would be a good addition here to ensure this remains working.

2023-11-27 11:27 UTC, languitar commented on commitlint.config.js
> +  ],
Can we lift this change into a separate chore/build commit?

2023-11-27 12:47 UTC, slisson commented
The new tests revealed unknown bugs. Looks like I have to fix them as well.

2023-11-27 14:26 UTC, slisson commented
The failing new tests will be fixed in a separate PR https://github.com/modelix/modelix.core/pull/343, because they are unrelated to the transaction handling bug fixed by this PR.

2023-11-27 14:31 UTC, languitar commented
As the test is not part of the commit that fixes the bug, I am lost which of tests is actually intended to verify the fixed bug. Can you give me a pointer?

2023-12-15 11:29 UTC, slisson commented
There are now unit tests that ensure the Ignite and map based implementation of IStoreClient behave the same.

2023-12-19 06:02 UTC, merged

2023-12-19 08:13 UTC, slisson commented
:tada: This PR is included in version 3.17.0 :tada:

The release is available on [GitHub release](https://github.com/modelix/modelix.core/releases/tag/3.17.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: