feat(model-server)!: Use ENTRYPOINT instead of CMD in the provided Docker image
modelix/modelix.core pull request #391
Opened 2024-01-03 15:33 UTC by odzhychko

> You can use the exec form of ENTRYPOINT to set fairly stable default commands and arguments and then use either form of CMD to set additional defaults that are more likely to be changed.
See. https://docs.docker.com/engine/reference/builder/#exec-form-entrypoint-example

Using a ENTRYPOINT in model-server docker container makes passing arguments easier. For example,
`docker run --rm -p 28101:28101 -it modelix/model-server ./run-model-server.sh -inmemory` would be simplified to
`docker run --rm -p 28101:28101 -it modelix/model-server -inmemory`

This is a breaking change, because the previous ENTRYPOINT was the default `ENTRYPOINT ["/bin/sh", "-c"]`.

2024-01-03 15:36 UTC, odzhychko commented
Currently, we have no documentation about the arguments of the model server and the docker container.
We have this [issue](https://issues.modelix.org/issue/MODELIX-575/Document-configuration-of-the-model-server) for this.

2024-01-03 16:03 UTC, languitar requested changes
In your commit message, you can use the `BREAKING CHANGE` trailer to explain what is breaking and how users get around it. That text goes into the changelog.

See here for an example: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

2024-01-08 08:22 UTC, languitar approved these changes

2024-01-08 14:44 UTC, merged

2024-01-09 02:22 UTC, slisson commented
:tada: This PR is included in version 4.0.0 :tada:

The release is available on [GitHub release](https://github.com/modelix/modelix.core/releases/tag/4.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: