MODELIX-846 Null-References lead to exception in data explorer
modelix/modelix.core pull request #660
Opened 2024-04-02 13:50 UTC by mhuster23

2024-04-02 14:07 UTC, languitar requested changes
Can we add a test for this?

2024-04-03 13:13 UTC, mhuster23 commented
![image](https://github.com/modelix/modelix.core/assets/122882121/37e23f77-45ef-4136-9619-edb3468dbd99)
This is how the information is displayed now.

2024-04-03 13:17 UTC, languitar submitted a review, later dismissed

2024-04-03 14:14 UTC, odzhychko approved these changes

2024-04-03 14:14 UTC, merged

2024-04-04 02:16 UTC, slisson commented
:tada: This PR is included in version 7.1.0 :tada:

The release is available on [GitHub release](https://github.com/modelix/modelix.core/releases/tag/7.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: