fix(model-server): make initial branch created through V2 API visible in V1 API
modelix/modelix.core pull request #715
Opened 2024-04-25 10:18 UTC by odzhychko

Writing to a branch through V2 API already makes a branch visible through the V1 API. Making the branch visible after initial creation makes the backwards compatibility more consistent.

I found this issue while reviewing and testing #714

2024-04-25 11:42 UTC, languitar commented
This should probably be a draft until a rebase after merging #714?

2024-04-25 11:44 UTC, languitar requested changes

2024-04-25 11:44 UTC, languitar commented on model-server/src/test/kotlin/org/modelix/model/server/handlers/ModelReplicationServerBackwardsCompatibilityTest.kt
> +    fun `master branch of repository initialized by V2 API is visible through V2 API`() {
One of them should be V1?

2024-04-29 10:00 UTC, odzhychko commented on model-server/src/test/kotlin/org/modelix/model/server/handlers/ModelReplicationServerBackwardsCompatibilityTest.kt
> +    fun `master branch of repository initialized by V2 API is visible through V2 API`() {
Yes. Done.

2024-04-29 10:03 UTC, languitar approved these changes

2024-04-29 10:09 UTC, merged

2024-04-30 02:16 UTC, slisson commented
:tada: This PR is included in version 7.3.1 :tada:

The release is available on [GitHub release](https://github.com/modelix/modelix.core/releases/tag/7.3.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: